AWSTemplateFormatVersion: "2010-09-09"
Description: A  VPC Template
Resources:
  VPC: 
    Type: "AWS::EC2::VPC"
    Properties: 
      CidrBlock: 10.0.0.0/16
      InstanceTenancy: default
      Tags:
       - Key: Name
         Value: IBM
         
          InternetGateway: # IBM Internet Gateway
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: IBM-IGW 
        
        AttachGateway: # Attach Internet Gateway - IBM VPC
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
         Ref: VPC
      InternetGatewayId:
         Ref: InternetGateway
         
         PubSubnet1: # Public Subnet
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.0.0/24
      AvailabilityZone: "us-east-1a"
      MapPublicIpOnLaunch: 'true'
      Tags:
      - Key: Name
        Value: IBM-Pub-SUBNET1
        
        

  PvtSubnet1: # Private Subnet
    Type: AWS::EC2::Subnet
    Properties:
      VpcId:
        Ref: VPC
      CidrBlock: 10.0.1.0/24
      AvailabilityZone: "us-east-1b"
      MapPublicIpOnLaunch: 'false'
      Tags:
      - Key: Name
        Value: IBM-Pvt-Subnet1
        
        PublicRouteTable: # Public Route Table
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: VPC
      Tags:
      - Key: Name
        Value: IBM-Pub-RT
        
        PrivateRouteTable: # Private Route Table
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: VPC
      Tags:
      - Key: Name
        Value: IBM-Pvt-RT  
        
        PublicRoute: # Route To IGW
    Type: AWS::EC2::Route
    DependsOn: AttachGateway
    Properties:
       RouteTableId:
         Ref: PublicRouteTable
       DestinationCidrBlock: 0.0.0.0/0
       GatewayId:
         Ref: InternetGateway
         
         PubSubnetRouteTableAssociation: # Pub Sub Association
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PubSubnet1
      RouteTableId:
        Ref: PublicRouteTable
        
         PvtSubnetRouteTableAssociation: # Pvt Sub Association
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PvtSubnet1
      RouteTableId:
        Ref: PrivateRouteTable

  






