AWSTemplateFormatVersion: "2010-09-09"
Description: A  VPC Template
Resources:
  VPC: 
    Type: "AWS::EC2::VPC"
    Properties: 
      CidrBlock: 10.0.0.0/16
      InstanceTenancy: default
      Tags:
       - Key: Name
         Value: IBM
